# Generated by Django 5.1.5 on 2025-04-06 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_cart'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='subscription_plan',
        ),
        migrations.AddField(
            model_name='cart',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='cart',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
