# Generated by Django 5.1.5 on 2025-04-08 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_customerwallet_customertransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='admintransaction',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='admintransaction',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.subscriptionplan'),
        ),
    ]
