# Generated by Django 5.1.5 on 2025-04-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_admintransaction_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='developertransaction',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
