# Generated by Django 5.1.5 on 2025-04-17 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codecontent',
            name='image_preview',
            field=models.ImageField(blank=True, null=True, upload_to='code_previews/'),
        ),
    ]
