# Generated by Django 5.1.5 on 2025-04-19 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_codecontent_image_preview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codecontent',
            name='tags',
        ),
        migrations.AlterField(
            model_name='codecontent',
            name='category',
            field=models.CharField(choices=[('web', 'Web Design'), ('card', 'Cards'), ('checkbox', 'Checkbox'), ('button', 'Button'), ('switch', 'Switch'), ('icon', 'Icon'), ('form', 'Form'), ('toggle', 'Toggle'), ('input', 'Input'), ('slider', 'Slider'), ('dropdown', 'Dropdown'), ('modal', 'Modal'), ('accordion', 'Accordion'), ('tabs', 'Tabs'), ('alert', 'Alert'), ('hover', 'Hover'), ('responsive', 'Responsive'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
