# Generated by Django 5.1.5 on 2025-04-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='social_media_links',
        ),
        migrations.RemoveField(
            model_name='developerprofile',
            name='social_media_links',
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='github_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='instagram_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='linkedIn_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='x_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='developerprofile',
            name='github_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='developerprofile',
            name='instagram_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='developerprofile',
            name='linkedIn_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='developerprofile',
            name='x_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
