# Generated by Django 5.1.5 on 2025-04-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_customerprofile_social_media_links_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developerprofile',
            name='bio',
            field=models.TextField(default=''),
        ),
    ]
