# Generated by Django 5.1.5 on 2025-04-03 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_developerprofile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developerprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
