# Generated by Django 5.1.5 on 2025-04-08 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_customerprofile_has_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='has_subscription',
        ),
    ]
