# Generated by Django 5.1.5 on 2025-04-08 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('advance_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('full_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('advance_paid', 'Advance Paid'), ('completed', 'Completed'), ('disputed', 'Disputed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('thread', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chat.chatthread')),
            ],
        ),
    ]
