# Generated by Django 5.1.5 on 2025-04-08 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_modificationrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modificationrequest',
            old_name='requested_price',
            new_name='counter_price',
        ),
        migrations.AddField(
            model_name='modificationrequest',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='modificationrequest',
            name='proposed_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='modificationrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('negotiating', 'Negotiating'), ('price_confirmed', 'Price Confirmed'), ('advance_paid', 'Advance Paid'), ('completed', 'Completed'), ('disputed', 'Disputed'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
    ]
