# Generated by Django 5.1.5 on 2025-04-09 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_rename_requested_price_modificationrequest_counter_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modificationrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('negotiating', 'Negotiating'), ('price_confirmed', 'Price Confirmed'), ('advance_paid', 'Advance Paid'), ('code_delivered', 'Code Delivered'), ('completed', 'Completed'), ('disputed', 'Disputed'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
    ]
