# Generated by Django 5.1.5 on 2025-04-10 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_modificationrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='modificationrequest',
            name='preview_token',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
