# Generated by Django 5.1.5 on 2025-04-10 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_modificationrequest_preview_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='modificationrequest',
            name='preview_count',
            field=models.IntegerField(default=0),
        ),
    ]
