# Generated by Django 5.1.5 on 2025-04-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_modificationrequest_preview_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modificationrequest',
            old_name='preview_count',
            new_name='customer_preview_count',
        ),
        migrations.AddField(
            model_name='modificationrequest',
            name='developer_preview_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='modificationrequest',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='chat_attachments/%Y/%m/%d/'),
        ),
    ]
