# Generated by Django 5.1.5 on 2025-04-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_rename_preview_count_modificationrequest_customer_preview_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modificationrequest',
            name='dispute_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modificationrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('negotiating', 'Negotiating'), ('price_confirmed', 'Price Confirmed'), ('advance_paid', 'Advance Paid'), ('code_delivered', 'Code Delivered'), ('completed', 'Completed'), ('disputed', 'Disputed'), ('declined', 'Declined'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
    ]
